// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtmqrjdqomovbkdabvqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bXFyamRxb21vdmJrZGFidnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTcxOTIsImV4cCI6MjA3Njg5MzE5Mn0.FBtj5W24t4BjKSRsQT6Z81JaQY1CUb8DggG_I6aDmoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});